description: Created
content:
  application/json:
    schema:
      properties:
        code:
          type: integer
          example: 201
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "ok"
        data:
          type: array
          items:
            type: string