openapi: "3.0.2"
info:
  title: SMS gateway
  description: "yet another driver based service for sending sms"
  version: "1.0.0"
servers:
  - url: https://localhost/api/v1

paths:

   /messages:
    $ref: "./messages/send.yml"


components:
  responses:
    # ----------------------------------------------------------------
    #   General Response
    # ----------------------------------------------------------------

    201:
      $ref: "./Responses/201.yml"
    403:
      $ref: "./Responses/403.yml"
    404:
      $ref: "./Responses/404.yml"
    500:
      $ref: "./Responses/500.yml"
